name: tasorderan
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  hive: ^2.2.3
  simple_fontellico_progress_dialog: ^0.3.0
  dio: ^5.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  otp_text_field: ^1.1.3
  quickalert: ^1.0.1
  material_dialogs: ^1.1.4
  lottie: ^2.6.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/shipping-truck.json
    - assets/imgs/updated-transaction.json
    - assets/imgs/onboarding-free.png
    - assets/imgs/bgapps.png
    - assets/imgs/bgapps2.png
    - assets/imgs/taslogo.png
    - assets/imgs/truckmin.jpg
    - assets/imgs/bg-bayar.jpg
    - assets/imgs/checklist.png
    - assets/imgs/register-bg.jpg
    - assets/imgs/user.png
    - assets/imgs/truck_done.gif
    - assets/imgs/trucking.png
    - assets/imgs/cross.png
    - assets/imgs/truck.jpg
    - assets/imgs/stuffing.png
    - assets/imgs/shipping_container.png
    - assets/imgs/order.png
    - assets/imgs/booking_proccess.png
    - assets/imgs/warehouse_container.png
    - assets/imgs/kapal-tiba.png
    - assets/imgs/kapal-sandar.png
    - assets/imgs/out-depo.png
    - assets/imgs/otp-verification.png
    - assets/imgs/success-refund.png
    - assets/imgs/border.png
    - assets/imgs/process-file.png
    - assets/imgs/no-internet.json
    - assets/imgs/refund-process.png
    - assets/imgs/refund-animation.json
    - assets/imgs/not-found.json
    - assets/imgs/carousel.jpg
    - assets/imgs/check.json
    - assets/imgs/send-email.json
    - assets/imgs/user-denied.json
    - assets/imgs/cancel-order.json
    - assets/imgs/bg-login.jpg
    - assets/imgs/checklogo.png
    - assets/imgs/idcard-scan.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito-Light.ttf
          # - asset: assets/fonts/Montserrat-Bold.ttf
          #   weight: 600
      - family: Cooper
        fonts:
          - asset: assets/fonts/Cooper-Light.ttf
            weight: 600
      - family: Nunito-ExtraBold
        fonts:
          - asset: assets/fonts/Nunito-ExtraBold.ttf
      - family: Nunito-Medium
        fonts:
          - asset: assets/fonts/Nunito-Medium.ttf 
      - family: Oxanium-Reguler
        fonts:
          - asset: assets/fonts/Oxanium-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
