name: tasorderan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  simple_fontellico_progress_dialog: ^0.3.0
  dio: ^5.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  otp_text_field: ^1.1.3
  quickalert: ^1.0.1
  material_dialogs: ^1.1.4
  lottie: ^2.6.0
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.3.2
  carousel_slider: ^4.2.1
  path_provider: ^2.1.1
  intl: ^0.18.1
  currency_text_input_formatter: ^2.1.10
  dropdown_search: ^2.0.0
  google_maps_place_picker_mb: ^3.0.2
  pdf: ^3.10.4
  flutter_pdfview: ^1.3.1
  camera: ^0.10.5+4
  image: ^4.0.17
  dotted_border: ^2.0.0+3
  mask_text_input_formatter: ^2.5.0
  pusher_client: ^2.0.0
  wakelock: ^0.6.2
  equatable: ^2.0.5
  google_maps_flutter: ^2.5.0
  timeline_tile: ^2.0.0
  # pusher_channels_flutter: ^2.2.0
  mnc_identifier_ocr: ^1.0.20
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/icon.png"
  min_sdk_android: 33

flutter_native_splash:
  color: "#b50d0d"
  image: assets/imgs/taslogo.png
  android_disable_fullscreen: true
  android: true
  ios: true
  web: true
  android_12:
    color: "#b50d0d"
    image: assets/imgs/taslogo.png
    android_disable_fullscreen: true


flutter:
  uses-material-design: true

  assets:
    - assets/imgs/shipping-truck.json
    - assets/imgs/updated-transaction.json
    - assets/imgs/onboarding-free.png
    - assets/imgs/bgapps.png
    - assets/imgs/bgapps2.png
    - assets/imgs/taslogo.png
    - assets/imgs/truckmin.jpg
    - assets/imgs/bg-bayar.jpg
    - assets/imgs/checklist.png
    - assets/imgs/register-bg.jpg
    - assets/imgs/user.png
    - assets/imgs/truck_done.gif
    - assets/imgs/trucking.png
    - assets/imgs/cross.png
    - assets/imgs/truck.jpg
    - assets/imgs/stuffing.png
    - assets/imgs/shipping_container.png
    - assets/imgs/order.png
    - assets/imgs/booking_proccess.png
    - assets/imgs/warehouse_container.png
    - assets/imgs/kapal-tiba.png
    - assets/imgs/kapal-sandar.png
    - assets/imgs/out-depo.png
    - assets/imgs/otp-verification.png
    - assets/imgs/success-refund.png
    - assets/imgs/border.png
    - assets/imgs/process-file.png
    - assets/imgs/no-internet.json
    - assets/imgs/refund-process.png
    - assets/imgs/refund-animation.json
    - assets/imgs/not-found.json
    - assets/imgs/carousel.jpg
    - assets/imgs/check.json
    - assets/imgs/send-email.json
    - assets/imgs/user-denied.json
    - assets/imgs/cancel-order.json
    - assets/imgs/bg-login.jpg
    - assets/imgs/checklogo.png
    - assets/imgs/idcard-scan.json

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito-Light.ttf
          # - asset: assets/fonts/Montserrat-Bold.ttf
          #   weight: 600
      - family: Cooper
        fonts:
          - asset: assets/fonts/Cooper-Light.ttf
            weight: 600
      - family: Nunito-ExtraBold
        fonts:
          - asset: assets/fonts/Nunito-ExtraBold.ttf
      - family: Nunito-Medium
        fonts:
          - asset: assets/fonts/Nunito-Medium.ttf
      - family: Oxanium-Reguler
        fonts:
          - asset: assets/fonts/Oxanium-Regular.ttf